name: CookBook CI (Import → Index → Build → Pages)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  # Optional nightly rebuild
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write     # we push generated files
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  import_json:
    # Guard against endless loops when the bot commits generated files
    # (The push still triggers, but jobs skip immediately.)
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Sync to latest main
        run: |
          git fetch origin
          git checkout main
          git pull --ff-only origin main || true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps (scripts + mkdocs if needed)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install mkdocs mkdocs-material
          fi

      - name: Convert JSON → Markdown
        run: python scripts/json_to_markdown.py

      - name: Build indexes/tags (and cleanup)
        run: python scripts/build_indexes.py

      - name: Commit generated Markdown and indexes (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          git config --global safe.directory "$PWD"
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            # Stage all adds, modifications, and deletions in the recipes/ tree
            git add -A recipes

            git commit -m "chore: sync recipes + indexes" || echo "No changes to commit"

            # Auth and rebase to avoid non-fast-forward pushes
            git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git"
            git fetch origin
            git checkout main
            git pull --rebase origin main || true

            # Retry push a few times in case another job raced us
            for i in 1 2 3; do
              if git push origin main; then
                echo "Pushed successfully."
                exit 0
              fi
              echo "Push failed, refetching and rebasing… (attempt $i)"
              git fetch origin
              git pull --rebase origin main || true
              sleep 2
            done
            echo "Failed to push after 3 attempts." && exit 1
          else
            echo "No markdown/index changes to commit."
          fi

  build_site:
    if: github.actor != 'github-actions[bot]'
    needs: import_json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Sync to latest main
        run: |
          git fetch origin
          git checkout main
          git pull --ff-only origin main || true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs + theme
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install mkdocs mkdocs-material
          fi

      - name: MkDocs build
        run: mkdocs build --strict

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build_site
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4