name: Import JSON → Markdown, then Rebuild Site
on:
  push:
    branches: [ "main" ]
    paths:
      - "data/recipes/*.json"
      - "scripts/json_to_markdown.py"

jobs:
  import:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        # Omit persist-credentials:false so the GITHUB_TOKEN stays configured
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Convert JSON → Markdown
        run: python scripts/json_to_markdown.py

      - name: Commit generated Markdown (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.ref_name }}
          REPO: ${{ github.repository }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add recipes/**/*.md
            git commit -m "chore: generate markdown from JSON"
            # Ensure remote uses token (defensive)
            git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git"
            git push origin "HEAD:${BRANCH}"
          fi