name: Import JSON → Markdown, then Rebuild Site
on:
  push:
    branches: [ "main" ]
    paths:
      - "data/recipes/*.json"
      - "scripts/json_to_markdown.py"
jobs:
  import:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Convert JSON → Markdown
        run: python scripts/json_to_markdown.py
      - name: Commit generated Markdown
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add recipes/**/*.md
            git commit -m "chore: generate markdown from JSON"
            git push
          fi
