name: Lint Markdown
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: |
            **/*.md
      - name: Typos (spellcheck)
        uses: crate-ci/typos@v1.27.0